## 본인의 체질량지수 (BMI)를 산출하는 프로그램 ##
print("="*55)
print("■ 201945018 컴시과 3학년 A반 김지웅 실습 1")
print("■ 본인의 체질량지수(BMI)를 산출하는 프로그램")
print("-"*55)
height = eval(input(">> 키 입력(m)    : "))
weight = eval(input(">> 체중 입력(kg) : "))
result = weight / (height * height)
print("-"*55)
print(">> 본인의 BMI : ", result)
print("="*55)